#!/bin/bash

REPO_PWD=$(pwd)

function copy_vim_files()
{
    REPO_PATH=$REPO_PWD/vim
    HOME_PATH=$HOME/.vim

    ln -s $REPO_PATH/vimrc $HOME_PATH/vimrc
    ln -s $REPO_PATH/pack $HOME_PATH/pack
    ln -s $REPO_PATH/plugin $HOME_PATH/plugin

    install_vim_submodules
}

function install_vim_submodules()
{
    git submodule update --init --recursive
}
